# action.yaml
name: "Splunk AppInspect"
description: "Run Splunk App inspect API Calls on Add-on"
runs:
  using: "composite"
  steps:
    - name: 'Make response directory'
      uses: shell
      run: |
        mkdir response
        ls -la
    - name: 'Run Appinspect'
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      uses: shell
      run: |
        export ADDON_NAME=$(ls build/package/)
        echo ' --- Addon name is $ADDON_NAME'
        pip install requests
        python main.py "$USERNAME" "$PASSWORD" "$ADDON_NAME"