site_name: Splunk Add-on for Google Cloud Platform
site_author: Splunk

markdown_extensions:
  - toc:
      permalink: True
  - smarty
  - fenced_code
  - sane_lists
  - codehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

theme:
  name: "material"
  logo: "static/splunk-logo.png"
  favicon: "static/splunk.png"
  palette:
    primary: "black"
    accent: "orange"

extra_javascript:
  - https://splunk.github.io/addonfactory-docs-on-github-integration/javascripts/dist/build.js
extra_css:
  - static/styles.css

plugins:
  - search
  - print-site

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
strict: true

copyright: 'Splunk Documentation covered by: <a href="https://www.splunk.com/en_us/legal.html">Legal</a> | <a href="https://www.splunk.com/en_us/legal/terms/terms-of-use.html">Terms</a> | <a href="https://www.splunk.com/en_us/legal/privacy/privacy-policy.html">Privacy</a></br>© Copyright 2024 Splunk Inc. All rights reserved. <br/>Webpages built on GitHub Pages | <a href="https://docs.github.com/en/site-policy/github-terms/github-terms-of-service">GitHub Terms</a> | <a href="https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement">GitHub Privacy</a>'

nav:
  - Overview:
    - Introduction: 'index.md'
    - Source types: 'Sourcetypes/index.md'
    - Release notes: 'Releasenotes/index.md'
    - Release history: 'Releasehistory/index.md'
    - Hardware and software requirements: 'Hardwareandsoftwarerequirements/index.md'
    - Installation overview: 'Installationoverview/index.md'
  - Installation:
    - Install: 'Installation/index.md'
    - Upgrade: 'Upgrade/index.md'
  - Configuration:
    - Configure the Google Cloud account: 'Setupv1/index.md'
    - Configure the Google Cloud Platform service permissions: 'Setupv3/index.md'
    - Set up the Add-on: 'Setupv2/index.md'
    - Configure Cloud Pub/Sub inputs: 'Configureinputsv1modular/index.md'
    - Configure Cloud Monitoring inputs: 'Configureinputsv2monitor/index.md'
    - Configure Cloud BigQuery Billing inputs: 'Configureinputsv3syslog/index.md'
    - Configure Cloud Storage Bucket inputs: 'Configureinputsv4storagebuckets/index.md'
    - Configure Resource Metadata inputs: 'Configureinputsv5resourcemetadata/index.md'
    - Configure Google Workspace audit logs: 'Configureinputsv6topics/index.md'
    - Configure Compute Engine inputs: 'Configureinputsv5computeengine/index.md'
    - Configure Cloud Storage inputs: 'Configureinputsv6cloudstorage/index.md'
    - Configure Kubernetes inputs: 'Configureinputsv7kubernetes/index.md'
    - Configure VPC Access inputs: 'Configureinputsv8vpcaccess/index.md'
    - Configure Cloud Pub/Sub Based Bucket inputs: 'Configureinputsmetadata/index.md'
    - Configure Cloud Pub/Sub Lite inputs: 'Configurelite/index.md'
    - Configure Resource Metadata inputs: 'Configureinputsauditlogs/index.md'
  - Troubleshoot:
    - Troubleshoot: 'Troubleshoot/index.md'
  - Reference:
    - Performance reference: 'Performancereference/index.md'
    - REST API reference: 'RESTAPIreference/index.md'
