name: test

on: workflow_dispatch

jobs:
    testing-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: false
                  persist-credentials: false
            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: package.spl
                path: dist/Splunk_TA_MS_Security-2.0.0.spl
            - name: download artifact
              uses: actions/download-artifact@v3
              with:
                name: package.spl
                path: artifacts/package.spl
            - name: LS
              run: ls -la
            - name: run python
              env:
                USERNAME: ${{ secrets.USERNAME }}
                PASSWORD: ${{ secrets.PASSWORD }}
              run: |
                pip install requests
                python main.py "$USERNAME" "$PASSWORD"
