name: test

on: workflow_dispatch

jobs:
    testing-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: false
                  persist-credentials: false
            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: package.spl
                path: dist/Splunk_TA_MS_Security-2.0.0.spl
            - name: download artifact
              uses: actions/download-artifact@v3
              id: download
              with:
                name: package.spl
                path: artifacts
            - name: LS
              run: ls -la
              working-directory: artifacts
            - name: 'Echo download path'
              run: export PACKAGE_NAME=$(ls artifacts -q)
            - name: run python
              env:
                USERNAME: ${{ secrets.USERNAME }}
                PASSWORD: ${{ secrets.PASSWORD }}
              run: |
                export ADDON_NAME=$(ls artifacts)
                echo ' --- Addon name is $ADDON_NAME'
                pip install requests
                python main.py "$USERNAME" "$PASSWORD" "$ADDON_NAME"
