name: test

on: workflow_dispatch

jobs:
    some-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: false
                  persist-credentials: false
            - name: run python
              run: |
                pip install requests
                python main.py
