name: test

on: workflow_dispatch

jobs:
    some-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: false
                  persist-credentials: false
            - name: appinspect
              uses: splunk/appinspect-api-action@v2
              with:
                  filePath: ./dist/Splunk_TA_MS_Security-2.0.0.spl
                  splunkUser: ${{ secrets.USERNAME }}
                  splunkPassword: ${{ secrets.PASSWORD }}
                  includedTags: cloud
                  failOnError: true
                  failOnWarning: true